version: '3.8'

services:
  api:
    build: .
    ports:
      - "8009:8009"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./patients_data.json:/app/patients_data.json:ro
    restart: unless-stopped
